# Generated by Django 4.1.7 on 2023-03-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_job_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="Published_ad",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="job", name="experance", field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="job", name="salary", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job", name="vancany", field=models.IntegerField(default=1),
        ),
    ]
